### ISSUE TITLE
Python version imcompatible with HTSeq

### ISSUE THREAD

**Issue by Zhixuan-Jing** [galelab/scViralQuant#2]
Hi, I'm trying to install scPathoQuant in my server. I used conda virtual environment with python version 3.12.2 and follow the instruction. But the error log indicates that the python version is too old, which comes from HTSeq (as shown below). COuld you help with that question?

<img width="1080" alt="37bb0a5814703aa7c6abcfdbd80113e" src="https://github.com/galelab/scPathoQuant/assets/57510261/0157e0c5-45c3-4f36-9741-d1bcfe26e1f3">

Best Regards,
Zhixuan

**Comment by lwhitmore** [comment]
@Zhixuan-Jing 
Hi Zhixuan, 
Thanks for the note.  I am going to try and replicate this but wanted to clarify, you mention you ran this on pythn 3.12.2 but your terminal output says you used  python version 3.6.3.  Did you happen to try both python versions?

Thanks!
Leanne

**Comment by lwhitmore** [comment]
Hi @Zhixuan-Jing,
I was able to replicate the error you had with python 3.6.  Because all the new htseq packages need at least 3.7 I updated scpathoquant to require python 3.8 or greater which was necessary for a couple other dependencies/packages as well. Note that the install instructions are now a bit different than in the previous version.   Hopefully this works better but please let me know if  there are new or other issues! Note that the install instructions are a bit different than in the previous version.

**Comment by lwhitmore** [comment]
This issue was fixed in most recent update
